/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo7.rentacar.JFrameInterfaz;

import grupo7.rentacar.Cliente.Cliente;
import grupo7.rentacar.Cliente.Categoria;
import grupo7.rentacar.Cliente.ListaCliente;
import grupo7.rentacar.Enumeraciones.Combustibles;
import javax.swing.JOptionPane;
import grupo7.rentacar.Vehiculos.ListaVehiculo;
import grupo7.rentacar.Vehiculos.Vehiculo;
import grupo7.rentacar.Enumeraciones.EstadoVehiculo;
import grupo7.rentacar.Extras.Extra;
import grupo7.rentacar.Extras.ListaExtras;
import grupo7.rentacar.Funciones;
public class JFrameInterfaz extends javax.swing.JFrame {


    private Funciones funciones = new Funciones();
    
    public JFrameInterfaz() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ButtonIngresarCliente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        labelCliente = new javax.swing.JTextField();
        labelCedula = new javax.swing.JTextField();
        labelFecha = new javax.swing.JTextField();
        labelCorreo = new javax.swing.JTextField();
        ButtonEliminar = new javax.swing.JButton();
        ButtonBuscarVehiculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaBuscar = new javax.swing.JTextArea();
        labelBEMcedula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ButtonIngresarVehiculo = new javax.swing.JButton();
        labelMarca = new javax.swing.JTextField();
        labelPlaca = new javax.swing.JTextField();
        labelColor = new javax.swing.JTextField();
        labelAño = new javax.swing.JTextField();
        labelModelo = new javax.swing.JTextField();
        labelCilindrada = new javax.swing.JTextField();
        labelNumPasajeros = new javax.swing.JTextField();
        Precio = new javax.swing.JTextField();
        BoxCombustible = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaVehiculos = new javax.swing.JTextArea();
        ButtonBuscarCliente = new javax.swing.JButton();
        labelBEMvehiculos = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ModificarClienteBoton = new javax.swing.JButton();
        ModificarCorreo = new javax.swing.JTextField();
        ModificarNacimiento = new javax.swing.JTextField();
        ModificarNombre = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextAreaEnlistar = new javax.swing.JTextArea();
        ButtonEliminarVehiculo = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextAreaEnlistarVehiculs = new javax.swing.JTextArea();
        Extra1 = new javax.swing.JCheckBox();
        Extra2 = new javax.swing.JCheckBox();
        Extra3 = new javax.swing.JCheckBox();
        Extra4 = new javax.swing.JCheckBox();
        Extra5 = new javax.swing.JCheckBox();
        ButtonEnlistarClientes = new javax.swing.JButton();
        labelCantMinAlquileres = new javax.swing.JTextField();
        labelCantDiasAlquiler = new javax.swing.JTextField();
        labelPreferencias = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ButtonSoliAlquiler = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TextAreaBuscarAlquiler = new javax.swing.JTextArea();
        BuscarPlaca1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        ButtonModificarVehiculo = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        ModificarMarca = new javax.swing.JTextField();
        ModificarPrecio = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        ModificarColor = new javax.swing.JTextField();
        ModificarModelo = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        ModificarCilin = new javax.swing.JTextField();
        ModificarNumPasa = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        ModificarAño = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        ButtonBuscarVehiculo2 = new javax.swing.JButton();
        ButtonEnlistarVehiculos1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        TextAreaBuscarAlquiler1 = new javax.swing.JTextArea();
        ButtonEnlistarAlquiler = new javax.swing.JButton();
        ComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Correo Electronico");

        jLabel3.setText("Nombre de Cliente");

        jLabel4.setText("Cedula");

        jLabel5.setText("Fecha de Nacimiento");

        ButtonIngresarCliente.setBackground(new java.awt.Color(102, 102, 255));
        ButtonIngresarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonIngresarCliente.setText("Ingresar Cliente");
        ButtonIngresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIngresarClienteActionPerformed(evt);
            }
        });

        labelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelClienteActionPerformed(evt);
            }
        });

        labelCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelCorreoActionPerformed(evt);
            }
        });

        ButtonEliminar.setBackground(new java.awt.Color(255, 102, 102));
        ButtonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonEliminar.setText("Eliminar Cliente");
        ButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarActionPerformed(evt);
            }
        });

        ButtonBuscarVehiculo.setBackground(new java.awt.Color(255, 255, 51));
        ButtonBuscarVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonBuscarVehiculo.setText("Buscar Alquiler");
        ButtonBuscarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarVehiculoActionPerformed(evt);
            }
        });

        TextAreaBuscar.setColumns(20);
        TextAreaBuscar.setRows(5);
        jScrollPane1.setViewportView(TextAreaBuscar);

        labelBEMcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelBEMcedulaActionPerformed(evt);
            }
        });

        jLabel8.setText("Cedula");

        ButtonIngresarVehiculo.setBackground(new java.awt.Color(0, 204, 0));
        ButtonIngresarVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonIngresarVehiculo.setText("Ingresar Vehiculo");
        ButtonIngresarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIngresarVehiculoActionPerformed(evt);
            }
        });

        labelMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelMarcaActionPerformed(evt);
            }
        });

        labelPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelPlacaActionPerformed(evt);
            }
        });

        labelColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelColorActionPerformed(evt);
            }
        });

        labelAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelAñoActionPerformed(evt);
            }
        });

        labelModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelModeloActionPerformed(evt);
            }
        });

        labelCilindrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelCilindradaActionPerformed(evt);
            }
        });

        labelNumPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelNumPasajerosActionPerformed(evt);
            }
        });

        Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioActionPerformed(evt);
            }
        });

        BoxCombustible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina", "Diesel", "Super", "Electrico" }));

        jLabel9.setText("Año del Vehiculo");

        jLabel10.setText("Marca de Vehiculo");

        jLabel11.setText("Numero de pasajeros");

        jLabel12.setText("Cilindrada de Vehiculo");

        jLabel13.setText("Modelo del Vehiculo");

        jLabel14.setText("Precio aproximado");

        jLabel15.setText("Placa de Vehiculo");

        jLabel16.setText("Color de Vehiculo");

        jLabel17.setText("Tipo de Combustible");

        TextAreaVehiculos.setColumns(20);
        TextAreaVehiculos.setRows(5);
        jScrollPane2.setViewportView(TextAreaVehiculos);

        ButtonBuscarCliente.setBackground(new java.awt.Color(102, 102, 255));
        ButtonBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonBuscarCliente.setText("Buscar Cliente");
        ButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarClienteActionPerformed(evt);
            }
        });

        labelBEMvehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelBEMvehiculosActionPerformed(evt);
            }
        });

        jLabel18.setText("Placa");

        jLabel21.setText("Fecha de Nacimiento");

        ModificarClienteBoton.setBackground(new java.awt.Color(102, 102, 255));
        ModificarClienteBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ModificarClienteBoton.setText("Modificar Cliente");
        ModificarClienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarClienteBotonActionPerformed(evt);
            }
        });

        ModificarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarCorreoActionPerformed(evt);
            }
        });

        ModificarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarNombreActionPerformed(evt);
            }
        });

        jLabel19.setText("Correo Electronico");

        jLabel20.setText("Nombre de Cliente");

        TextAreaEnlistar.setColumns(20);
        TextAreaEnlistar.setRows(5);
        jScrollPane3.setViewportView(TextAreaEnlistar);

        ButtonEliminarVehiculo.setBackground(new java.awt.Color(255, 102, 102));
        ButtonEliminarVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonEliminarVehiculo.setText("Eliminar Vehiculo");
        ButtonEliminarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarVehiculoActionPerformed(evt);
            }
        });

        TextAreaEnlistarVehiculs.setColumns(20);
        TextAreaEnlistarVehiculs.setRows(5);
        jScrollPane4.setViewportView(TextAreaEnlistarVehiculs);

        Extra1.setText("Arranque sin llave");
        Extra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Extra1ActionPerformed(evt);
            }
        });

        Extra2.setText("Navegador con trafico en vivo");
        Extra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Extra2ActionPerformed(evt);
            }
        });

        Extra3.setText("Sensores");

        Extra4.setText("Camara con vision trasera");

        Extra5.setText("Conectividad con cargador inalambrico");
        Extra5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Extra5ActionPerformed(evt);
            }
        });

        ButtonEnlistarClientes.setBackground(new java.awt.Color(255, 102, 102));
        ButtonEnlistarClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonEnlistarClientes.setText("Enlistar Clientes");
        ButtonEnlistarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnlistarClientesActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("SOLICITUDES DE ALQUILER");

        jLabel23.setText("Cantidad de dias para alquiler del vehiculo");

        jLabel24.setText("Cantidad minimade pasjeros");

        jLabel25.setText("Preferencias de marca, modelo o año");

        ButtonSoliAlquiler.setBackground(new java.awt.Color(255, 255, 51));
        ButtonSoliAlquiler.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonSoliAlquiler.setText("Solicitar Alquiler");
        ButtonSoliAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSoliAlquilerActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("VEHICULOS");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setText("CLIENTES");

        TextAreaBuscarAlquiler.setColumns(20);
        TextAreaBuscarAlquiler.setRows(5);
        jScrollPane5.setViewportView(TextAreaBuscarAlquiler);

        BuscarPlaca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPlaca1ActionPerformed(evt);
            }
        });

        jLabel28.setText("Placa");

        ButtonModificarVehiculo.setBackground(new java.awt.Color(0, 204, 0));
        ButtonModificarVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonModificarVehiculo.setText("Modificar Vehiculo");
        ButtonModificarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModificarVehiculoActionPerformed(evt);
            }
        });

        jLabel22.setText("Precio aproximado");

        ModificarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarMarcaActionPerformed(evt);
            }
        });

        ModificarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarPrecioActionPerformed(evt);
            }
        });

        jLabel29.setText("Marca de Vehiculo");

        jLabel30.setText("Modelo del Vehiculo");

        jLabel31.setText("Color de Vehiculo");

        ModificarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarColorActionPerformed(evt);
            }
        });

        ModificarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarModeloActionPerformed(evt);
            }
        });

        jLabel32.setText("Cilindrada de Vehiculo");

        ModificarCilin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarCilinActionPerformed(evt);
            }
        });

        ModificarNumPasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarNumPasaActionPerformed(evt);
            }
        });

        jLabel33.setText("Numero de pasajeros");

        ModificarAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarAñoActionPerformed(evt);
            }
        });

        jLabel34.setText("Año del Vehiculo");

        ButtonBuscarVehiculo2.setBackground(new java.awt.Color(0, 204, 0));
        ButtonBuscarVehiculo2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonBuscarVehiculo2.setText("Buscar Vehiculo");
        ButtonBuscarVehiculo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarVehiculo2ActionPerformed(evt);
            }
        });

        ButtonEnlistarVehiculos1.setBackground(new java.awt.Color(255, 102, 102));
        ButtonEnlistarVehiculos1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonEnlistarVehiculos1.setText("Enlistar Vehiculos");
        ButtonEnlistarVehiculos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnlistarVehiculos1ActionPerformed(evt);
            }
        });

        TextAreaBuscarAlquiler1.setColumns(20);
        TextAreaBuscarAlquiler1.setRows(5);
        jScrollPane6.setViewportView(TextAreaBuscarAlquiler1);

        ButtonEnlistarAlquiler.setBackground(new java.awt.Color(255, 255, 51));
        ButtonEnlistarAlquiler.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonEnlistarAlquiler.setText("Enlistar Alquiler");

        ComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bronce", "Plata", "Oro", "Zafiro", " " }));

        jLabel35.setText("Categoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ModificarClienteBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(18, 18, 18)
                                    .addComponent(ModificarCorreo))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ModificarNacimiento))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addGap(18, 18, 18)
                                    .addComponent(ModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelBEMcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ButtonIngresarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel35))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelFecha)
                                        .addComponent(labelCorreo)
                                        .addComponent(labelCliente)
                                        .addComponent(labelCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(ButtonEnlistarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(31, 31, 31)
                                                    .addComponent(jLabel18)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(labelBEMvehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(ButtonBuscarVehiculo2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(ButtonEliminarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(5, 5, 5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(ButtonModificarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel29)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(ModificarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel22)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(ModificarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel34)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(ModificarAño, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel32)
                                                        .addComponent(jLabel33))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ModificarNumPasa, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ModificarCilin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(jLabel30)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel31)
                                                            .addGap(21, 21, 21)))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(ModificarColor)
                                                        .addComponent(ModificarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(ButtonIngresarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(295, 295, 295)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(ButtonEnlistarVehiculos1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(BoxCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(101, 101, 101))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelColor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel15))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(labelPlaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelNumPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelCilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelAño, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Extra2)
                                    .addComponent(Extra1)
                                    .addComponent(Extra5)
                                    .addComponent(Extra4)
                                    .addComponent(Extra3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addGap(405, 405, 405)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(ButtonSoliAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addGap(18, 18, 18)
                                    .addComponent(labelCantMinAlquileres))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelPreferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(labelCantDiasAlquiler))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(67, 67, 67)
                                            .addComponent(jLabel6)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonBuscarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BuscarPlaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ButtonEnlistarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(labelMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(labelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(labelCilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel15)
                                            .addComponent(labelPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(labelNumPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addComponent(Extra1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(Extra2)
                                .addGap(13, 13, 13)
                                .addComponent(Extra3)
                                .addGap(12, 12, 12)
                                .addComponent(Extra4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Extra5)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BoxCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(ButtonIngresarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel29)
                                            .addComponent(ModificarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ModificarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ModificarColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel31))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ModificarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel30))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ModificarNumPasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel33))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ModificarCilin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel32))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ModificarAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel34))
                                        .addGap(18, 18, 18)
                                        .addComponent(ButtonModificarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(labelBEMvehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ButtonBuscarVehiculo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ButtonEliminarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonEnlistarVehiculos1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelCantMinAlquileres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelPreferencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelCantDiasAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(ButtonSoliAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonEnlistarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BuscarPlaca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonBuscarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonEnlistarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel35))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonIngresarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(ModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(ModificarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ModificarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ModificarClienteBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBEMcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonIngresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIngresarClienteActionPerformed
        String nom = "", fch = "", correo = "";
        int cedu = 0;
        if ( // Verificamos que los datos del cliente no esté vacíos
                labelCliente.getText().equals("")
                || labelCedula.getText().equals("")
                || labelFecha.getText().equals("")
                || labelCorreo.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    null,
                    "Error: Datos del cliente faltantes",
                    "Error: Cliente",
                    0
            );
        } else {

            try {
                nom = labelCliente.getText();
                cedu = Integer.parseInt(labelCedula.getText());
                fch = labelFecha.getText();
                correo = labelCorreo.getText();

                switch(ComboBoxCategoria.getSelectedIndex()){
            case 0:
              funciones.crearCliente(nom, fch, cedu, correo, Categoria.Bronce
                
                );
                break;
            case 1:
                funciones.crearCliente(nom, fch, cedu, correo, Categoria.Plata
                );
                break;
            case 2:
                funciones.crearCliente(nom, fch, cedu, correo, Categoria.Oro
                );
                break;
            case 3:
                funciones.crearCliente(nom, fch, cedu, correo, Categoria.Zafiro
                );
                break;
                }
                

                labelCliente.setText(null);
                labelCedula.setText(null);
                labelFecha.setText(null);
                labelCorreo.setText(null);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,
                        "Error: Informacion incompleta",
                        "Error: Informacion de cliente",
                        0
                );
            }
        }
    }//GEN-LAST:event_ButtonIngresarClienteActionPerformed

    private void labelCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelCorreoActionPerformed

    private void labelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelClienteActionPerformed

    private void ButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformed
        try {
            funciones.eliminarCliente(
                    Integer.parseInt(labelBEMcedula.getText())
            );
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    null, 
                    "Error: Cedula no válida", 
                    "Error: Cedula no válida", 
                    0
            );
        }

    }//GEN-LAST:event_ButtonEliminarActionPerformed

    private void labelBEMcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelBEMcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelBEMcedulaActionPerformed

    private void ButtonBuscarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarVehiculoActionPerformed
        TextAreaVehiculos.setText(funciones.getVehiculos()+"");

    }//GEN-LAST:event_ButtonBuscarVehiculoActionPerformed

    private void labelMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelMarcaActionPerformed

    private void labelPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelPlacaActionPerformed

    private void labelColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelColorActionPerformed

    private void labelAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelAñoActionPerformed

    private void labelModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelModeloActionPerformed

    private void labelCilindradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelCilindradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelCilindradaActionPerformed

    private void labelNumPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelNumPasajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelNumPasajerosActionPerformed

    private void PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioActionPerformed

    private void ButtonIngresarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIngresarVehiculoActionPerformed
        String col = "", plc = "", mar = "";
        Combustibles comb;
        int mod = 0, an = 0, np = 0, cilin = 0;
        double pre = 0;
        if ( // Verificamos que los datos del cliente no esté vacíos
                labelModelo.getText().equals(" ")
                || labelAño.getText().equals("")
                || labelCilindrada.getText().equals("")
                || labelColor.getText().equals("")
                || labelNumPasajeros.getText().equals("")
                || labelPlaca.getText().equals("")
                || Precio.getText().equals("")
                || labelMarca.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    null,
                    "Error: Datos del cliente faltantes",
                    "Error: Cliente",
                    0
            );
        } else {
            try {

                mod = Integer.parseInt(labelModelo.getText());
                cilin = Integer.parseInt(labelCilindrada.getText());
                col = labelColor.getText();
                plc = labelPlaca.getText();
                mar = labelMarca.getText();

                an = Integer.parseInt(labelAño.getText());
                np = Integer.parseInt(labelNumPasajeros.getText());
                pre = Double.parseDouble(Precio.getText());
                
                ListaExtras temp = new ListaExtras();
                if(Extra1.isSelected()){
                    Extra a = new Extra(Extra1.getText(),1);
                    temp.inserta(a);
                }
                if(Extra2.isSelected()){
                    Extra b = new Extra(Extra2.getText(),2);
                    temp.inserta(b);
                }
                if(Extra3.isSelected()){
                    Extra c = new Extra(Extra3.getText(),3);
                    temp.inserta(c);
                }
                if(Extra4.isSelected()){
                    Extra d = new Extra(Extra4.getText(),4);
                    temp.inserta(d);
                }
                if(Extra5.isSelected()){
                    Extra extra = new Extra(Extra5.getText(),5);
                    temp.inserta(extra);
                }
                switch(BoxCombustible.getSelectedIndex()){
            case 0:
              funciones.ingresarVehiculo(plc, mar, mod, 
                        an, col, cilin, np, 
                        pre, temp, Combustibles.Gasolina
                
                );
                break;
            case 1:
                funciones.ingresarVehiculo(plc, mar, mod, 
                        an, col, cilin, np, 
                        pre, temp, Combustibles.Diesel
                );
                break;
            case 2:
                funciones.ingresarVehiculo(plc, mar, mod, 
                        an, col, cilin, np, 
                        pre, temp, Combustibles.Super
                );
                break;
            case 3:
                funciones.ingresarVehiculo(plc, mar, mod, 
                        an, col, cilin, np, 
                        pre, temp, Combustibles.Electrico);
                break;
                }

                
                Extra1.setSelected(false);
                Extra2.setSelected(false);
                Extra3.setSelected(false);
                Extra4.setSelected(false);
                Extra5.setSelected(false);
                
                labelAño.setText(null);
                labelCilindrada.setText(null);
                labelMarca.setText(null);
                labelModelo.setText(null);
                labelPlaca.setText(null);
                labelNumPasajeros.setText(null);
                labelColor.setText(null);
                Precio.setText(null);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(
                        null,
                        "Error: Informacion incompleta",
                        "Error: Informacion de vehiculo",
                        0
                );
            }
        }
    }//GEN-LAST:event_ButtonIngresarVehiculoActionPerformed

    private void ButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarClienteActionPerformed
        Cliente cliente;
        try{
            cliente= funciones.buscarCliente(
                    Integer.parseInt(labelBEMcedula.getText())
            );
        }catch(Exception ex){
            JOptionPane.showMessageDialog(
                    null, 
                    "Error: Cedula no válida", 
                    "Error: Cedula no válida", 
                    0
            );
            cliente= null;
        }
        if(cliente != null){
            TextAreaBuscar.setText(cliente+"");
        }else{
            TextAreaBuscar.setText("-=Error=-\nCliente no encontrado");
        }

    }//GEN-LAST:event_ButtonBuscarClienteActionPerformed

    private void labelBEMvehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelBEMvehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelBEMvehiculosActionPerformed

    private void ModificarClienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarClienteBotonActionPerformed
        String nom = "", fch = "", correo = "";
        int cedu = 0;
        if ( // Verificamos que los datos del cliente no esté vacíos
                ModificarCorreo.getText().equals("")
                || ModificarNacimiento.getText().equals("")
                || labelBEMcedula.getText().equals("")
                || ModificarNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    null,
                    "Error: Datos del cliente faltantes",
                    "Error: Cliente",
                    0
            );
        } else {

            try {
                nom = ModificarNombre.getText();
                cedu = Integer.parseInt(labelBEMcedula.getText());
                fch = ModificarNacimiento.getText();
                correo = ModificarCorreo.getText();

                Cliente clienteN = new Cliente();

                clienteN.setNombre(nom);
                clienteN.setFechaNaci(fch);
                clienteN.setCedula(cedu);
                clienteN.setCorreoElec(correo);
                clienteN.setCategoria(Categoria.Bronce);
                
                funciones.modificarCliente(clienteN);
                //ingresarCliente(nom, fch, cedu, correo, Categoria.Bronce);

                ModificarCorreo.setText(null);
                ModificarNacimiento.setText(null);
                labelBEMcedula.setText(null);
                ModificarNombre.setText(null);
                
                //TextAreaEnlistar.setText(clientes.Listar());

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,
                        "Error: Informacion incompleta",
                        "Error: Informacion de cliente",
                        0
                );
            }
        }
    }//GEN-LAST:event_ModificarClienteBotonActionPerformed

    private void ModificarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarCorreoActionPerformed

    private void ModificarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarNombreActionPerformed

    }//GEN-LAST:event_ModificarNombreActionPerformed

    private void ButtonEliminarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarVehiculoActionPerformed
        try {
            funciones.eliminarVehiculo(labelBEMvehiculos.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    null, 
                    "Error: Cedula no válida", 
                    "Error: Cedula no válida", 
                    0
            );
        }        
    }//GEN-LAST:event_ButtonEliminarVehiculoActionPerformed

    private void Extra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Extra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Extra2ActionPerformed

    private void ButtonSoliAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSoliAlquilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSoliAlquilerActionPerformed

    private void BuscarPlaca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPlaca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarPlaca1ActionPerformed

    private void ButtonModificarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModificarVehiculoActionPerformed
        String col = "", mar = "", plc = "";
        int mod = 0, an = 0, np = 0, cilin = 0;
         double pre = 0;
        if ( // Verificamos que los datos del cliente no esté vacíos
                ModificarAño.getText().equals("")
                || ModificarCilin.getText().equals("")
                || labelBEMvehiculos.getText().equals("")
                || ModificarMarca.getText().equals("")
                || ModificarNumPasa.getText().equals("")
                || ModificarColor.getText().equals("")
                || ModificarModelo.getText().equals("")
                || ModificarPrecio.getText().equals("")
                || ModificarMarca.getText().equals("")) 
        {
            JOptionPane.showMessageDialog(
                    null,
                    "Error: Datos del cliente faltantes",
                    "Error: Cliente",
                    0
            );
        
        } else {
            try{
                mod = Integer.parseInt(ModificarModelo.getText());
                an = Integer.parseInt(ModificarAño.getText());
                mar = ModificarMarca.getText();
                col = ModificarColor.getText();
                cilin = Integer.parseInt(ModificarCilin.getText());
                np = Integer.parseInt(ModificarNumPasa.getText());
                pre = Double.parseDouble(ModificarPrecio.getText());
                plc = labelBEMvehiculos.getText();

                Vehiculo vehiculoN = new Vehiculo();

                vehiculoN.setPlaca(plc);
                vehiculoN.setMarca(mar);
                vehiculoN.setModelo(mod);
                vehiculoN.setAnno(an);
                vehiculoN.setColor(col);
                vehiculoN.setCilindrada(cilin);
                vehiculoN.setPasajeros(np);
                vehiculoN.setPrecio(pre);
                vehiculoN.setEstado(EstadoVehiculo.Disponible);
                
                funciones.modificarVehiculo(vehiculoN);
                
                ModificarAño.setText(null);
                ModificarCilin.setText(null);
                labelBEMvehiculos.setText(null);
                ModificarColor.setText(null);
                ModificarMarca.setText(null);
                ModificarNumPasa.setText(null);
                ModificarPrecio.setText(null);
                ModificarModelo.setText(null);
                
                
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,
                        "Error: Informacion incompleta",
                        "Error: Informacion de vehiculo",
                        0
                );
            }
        }   
    }//GEN-LAST:event_ButtonModificarVehiculoActionPerformed

    private void ButtonEnlistarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnlistarClientesActionPerformed
        TextAreaEnlistar.setText(funciones.getClientes() + "");
        
    }//GEN-LAST:event_ButtonEnlistarClientesActionPerformed

    private void ModificarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarMarcaActionPerformed

    private void ModificarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarPrecioActionPerformed

    private void ModificarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarColorActionPerformed

    private void ModificarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarModeloActionPerformed

    private void ModificarCilinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarCilinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarCilinActionPerformed

    private void ModificarNumPasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarNumPasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarNumPasaActionPerformed

    private void ModificarAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarAñoActionPerformed

    private void ButtonBuscarVehiculo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarVehiculo2ActionPerformed
        Vehiculo vehiculo;
        try{
            vehiculo= funciones.buscarVehiculo(
                    labelBEMvehiculos.getText()
            );
        }catch(Exception ex){
            JOptionPane.showMessageDialog(
                    null, 
                    "Error: Placa no válida", 
                    "Error: Placa no válida", 
                    0
            );
            vehiculo= null;
        }
        if(vehiculo != null){
            TextAreaVehiculos.setText(vehiculo+"");
        }else{
            TextAreaVehiculos.setText("-=Error=-\nVehículo no encontrado");
        }
    }//GEN-LAST:event_ButtonBuscarVehiculo2ActionPerformed

    private void ButtonEnlistarVehiculos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnlistarVehiculos1ActionPerformed
        TextAreaEnlistarVehiculs.setText(funciones.getVehiculos()+"");
    }//GEN-LAST:event_ButtonEnlistarVehiculos1ActionPerformed

    private void Extra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Extra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Extra1ActionPerformed

    private void Extra5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Extra5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Extra5ActionPerformed



    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxCombustible;
    private javax.swing.JTextField BuscarPlaca1;
    private javax.swing.JButton ButtonBuscarCliente;
    private javax.swing.JButton ButtonBuscarVehiculo;
    private javax.swing.JButton ButtonBuscarVehiculo2;
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JButton ButtonEliminarVehiculo;
    private javax.swing.JButton ButtonEnlistarAlquiler;
    private javax.swing.JButton ButtonEnlistarClientes;
    private javax.swing.JButton ButtonEnlistarVehiculos1;
    private javax.swing.JButton ButtonIngresarCliente;
    private javax.swing.JButton ButtonIngresarVehiculo;
    private javax.swing.JButton ButtonModificarVehiculo;
    private javax.swing.JButton ButtonSoliAlquiler;
    private javax.swing.JComboBox<String> ComboBoxCategoria;
    private javax.swing.JCheckBox Extra1;
    private javax.swing.JCheckBox Extra2;
    private javax.swing.JCheckBox Extra3;
    private javax.swing.JCheckBox Extra4;
    private javax.swing.JCheckBox Extra5;
    private javax.swing.JTextField ModificarAño;
    private javax.swing.JTextField ModificarCilin;
    private javax.swing.JButton ModificarClienteBoton;
    private javax.swing.JTextField ModificarColor;
    private javax.swing.JTextField ModificarCorreo;
    private javax.swing.JTextField ModificarMarca;
    private javax.swing.JTextField ModificarModelo;
    private javax.swing.JTextField ModificarNacimiento;
    private javax.swing.JTextField ModificarNombre;
    private javax.swing.JTextField ModificarNumPasa;
    private javax.swing.JTextField ModificarPrecio;
    private javax.swing.JTextField Precio;
    private javax.swing.JTextArea TextAreaBuscar;
    private javax.swing.JTextArea TextAreaBuscarAlquiler;
    private javax.swing.JTextArea TextAreaBuscarAlquiler1;
    private javax.swing.JTextArea TextAreaEnlistar;
    private javax.swing.JTextArea TextAreaEnlistarVehiculs;
    private javax.swing.JTextArea TextAreaVehiculos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField labelAño;
    private javax.swing.JTextField labelBEMcedula;
    private javax.swing.JTextField labelBEMvehiculos;
    private javax.swing.JTextField labelCantDiasAlquiler;
    private javax.swing.JTextField labelCantMinAlquileres;
    private javax.swing.JTextField labelCedula;
    private javax.swing.JTextField labelCilindrada;
    private javax.swing.JTextField labelCliente;
    private javax.swing.JTextField labelColor;
    private javax.swing.JTextField labelCorreo;
    private javax.swing.JTextField labelFecha;
    private javax.swing.JTextField labelMarca;
    private javax.swing.JTextField labelModelo;
    private javax.swing.JTextField labelNumPasajeros;
    private javax.swing.JTextField labelPlaca;
    private javax.swing.JTextField labelPreferencias;
    // End of variables declaration//GEN-END:variables
}
